version: '3.9'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
    container_name: lb
  ws1:
    image: wsapp
    environment:
      - APPID=1111
    container_name: ws1
  ws2:
    image: wsapp
    environment:
      - APPID=2222
    container_name: ws2
  ws3:
    image: wsapp
    environment:
      - APPID=3333
    container_name: ws3
  ws4:
    image: wsapp
    environment:
      - APPID=4444
    container_name: ws4
  rds:
    image: redis
    container_name: rds
